# Generated by Il2CppDumper for Binary Ninja
import json
import os
from binaryninja import Symbol, SymbolType

def run(bv):
    base = bv.start
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, 'script.json')
    if not os.path.exists(json_path):
        print('[-] script.json not found')
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    methods = data.get('ScriptMethod', [])
    count = 0
    for m in methods:
        rva = m.get('Rva', 0)
        if rva == 0: continue
        ea = base + rva
        name = m.get('Name', '').replace(' ', '_').replace('.', '_').replace('$', '_').replace('<', '_').replace('>', '_')
        bv.define_user_symbol(Symbol(SymbolType.FunctionSymbol, ea, name))
        sig = m.get('Signature', '')
        if sig:
            bv.set_comment_at(ea, sig)
        count += 1

    print(f'[+] Imported {count} symbols into Binary Ninja')

if __name__ == '__main__':
    pass
