# Generated by Il2CppDumper for Ghidra
# @category Il2Cpp
import json
import os

def run():
    base = currentProgram.getImageBase().getOffset()
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, 'script.json')
    if not os.path.exists(json_path):
        print('[-] script.json not found')
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    methods = data.get('ScriptMethods', [])
    print('Applying {} symbols in Ghidra...'.format(len(methods)))
    listing = currentProgram.getListing()
    for m in methods:
        rva = m.get('Rva', 0)
        if rva == 0: continue
        addr = currentAddress.getAddress(hex(base + rva))
        name = m.get('Name', '').replace(' ', '_').replace('.', '_').replace('$', '_').replace('<', '_').replace('>', '_')
        sig = m.get('Signature', '')
        func = getFunctionAt(addr)
        if func is None:
            func = createFunction(addr, name)
        else:
            func.setName(name, ghidra.program.model.symbol.SourceType.USER_DEFINED)
        if sig and func is not None:
            func.setRepeatableComment(sig)

    print('Ghidra symbol import complete.')

if __name__ == '__main__':
    run()
