# Generated by Il2CppDumper for Ghidra
# Run in Ghidra Script Manager: Add this script directory and run ghidra.py
import json
import os

def run():
    base = currentProgram.getImageBase().getOffset()
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, 'script.json')
    if not os.path.exists(json_path):
        print('[-] script.json not found at ' + json_path)
        return

    with open(json_path, 'r') as f:
        data = json.load(f)

    methods = data.get('ScriptMethod', [])
    count = 0
    for m in methods:
        rva = m.get('Rva', 0)
        if rva == 0: continue
        addr = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(base + rva)
        name = m.get('Name', '').replace(' ', '_').replace('.', '_').replace('$', '_').replace('<', '_').replace('>', '_')
        createFunction(addr, name)
        sig = m.get('Signature', '')
        if sig:
            setPlateComment(addr, sig)
        count += 1

    print('[+] Imported %d symbols into Ghidra' % count)

if __name__ == '__main__':
    run()
