# Generated by Il2CppDumper for IDA Pro
# Run in IDA Pro: File -> Script file... -> Select this ida.py
import idaapi
import idc
import idautils
import json
import os

def set_name(ea, name):
    idc.set_name(ea, name, idc.SN_CHECK | idc.SN_NOWARN)

def set_comment(ea, comment):
    idc.set_cmt(ea, comment, 1)

def run():
    base = idaapi.get_imagebase()
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, 'script.json')
    if not os.path.exists(json_path):
        print(f'[-] script.json not found at {json_path}')
        return

    print('[+] Loading script.json...')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    methods = data.get('ScriptMethods', [])
    print(f'[+] Applying {len(methods)} method symbols to IDA...')
    count = 0
    for m in methods:
        rva = m.get('Rva', 0)
        if rva == 0:
            continue
        ea = base + rva
        name = m.get('Name', '').replace(' ', '_').replace('.', '_').replace('$', '_').replace('<', '_').replace('>', '_')
        sig = m.get('Signature', '')
        set_name(ea, name)
        if sig:
            set_comment(ea, sig)
        count += 1

    print(f'[+] Renamed {count} functions successfully in IDA.')

if __name__ == '__main__':
    run()
